version: "3"

services:
  db:
    container_name: gocomdb
    image: postgres:13
    environment:
      POSTGRES_USER: gocom
      POSTGRES_PASSWORD: gocom123
      POSTGRES_DB: gocomdb
    ports:
      - 5432:5432
    networks:
      - default
    expose:
      - "5432"
    volumes:
      - ./schemas/local-data/db/gocomdb:/var/lib/postgresql/data

