apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: gocom-auth-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gocom-auth
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gocom-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gocomauth
  template:
    metadata:
      labels:
        app: gocomauth
    spec:
      containers:
      - name: auth
        imagePullPolicy: Always
        image: shahincsejnu/gocom-auth:1e0290f
        ports:
        - containerPort: 8080
        env:
          - name: DATABASE_URL
            value: postgresql://gocom:gocom123@10.0.0.15:5432/gocomdb?sslmode=disable
          - name: SECRET_KEY
            value: supersecretkey123
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: gocomauth
