apiVersion: apps/v1
kind: Deployment
metadata:
  name: gocom-ecom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gocomecom
  template:
    metadata:
      labels:
        app: gocomecom
    spec:
      containers:
      - name: ecom
        imagePullPolicy: Always
        image: shahincsejnu/gocom-ecom:a7a4b0a
        ports:
        - containerPort: 8080
        env:
          - name: DATABASE_URL
            value: postgresql://gocom:gocom123@postgres-service:5432/gocomdb?sslmode=disable
---
apiVersion: v1
kind: Service
metadata:
  name: ecom-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: gocomecom
