apiVersion: apps/v1
kind: Deployment
metadata:
  name: gocom-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gocomfe
  template:
    metadata:
      labels:
        app: gocomfe
    spec:
      containers:
      - name: fe
        imagePullPolicy: Always
        image: shahincsejnu/gocom-frontend:1e0290f
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ecom-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: gocomfe
