apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gocom-argocd-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shahincsejnu/gocom
    path: schemas/manifests/k8s
    targetRevision: HEAD
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
