openapi: 3.0.0
info:
  version: '1.0'
  title: Ecom Service
  description: Service for ecom CRUD operations in gocom.
  contact:
    name: gocom
    url: 'https://github.com/shahincsejnu/gocom'
    email: gocom@gmail.com
servers:
  - url: 'http://localhost:8085'
    description: local
tags:
  - name: ecom
paths:
  '/':
    GET:
      summary: Healthcheck.
      description: Healthcheck.
      operationId: healthcheck
      tags:
        - Healthcheck
      responses:
        '200':
          description: Healthcheck succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  serviceName:
                    type: string
                    example: EcomService
                required:
                  - ok
                  - serviceName
  '/users/{userID}':
    parameters:
      - name: userID
        in: path
        required: true
        schema:
          type: string
        description: user id of the respective user
    get:
      summary: Get user by userID.
      description: Get the details of a user with userID.
      operationId: get-one-user-by-userid
      tags:
        - User
      responses:
        '200':
          description: User fetching is succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  message:
                    type: string
                  user:
                    $ref: '#/components/schemas/user'
                required:
                  - ok
                  - message
                  - user
  /products:
    get:
      summary: Get all the products
      description: Get the details of all products
      operationId: get-all-products
      tags:
        - Products
      responses:
        '200':
          description: Products fetching is succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  message:
                    type: string
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/product'
                required:
                  - ok
                  - message
                  - products
    post:
      summary: Create a product
      description: To create/add a new product
      operationId: create-one-product
      tags:
        - Create Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                description:
                  type: string
                stock:
                  type: number
              required:
                - name
                - price
                - description
                - stock
      responses:
        '200':
          description: Product creation is succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  message:
                    type: string
                  productID:
                    type: string
                required:
                  - ok
                  - message
                  - productID
  '/products/{productID}':
    parameters:
      - name: productID
        in: path
        required: true
        schema:
          type: string
        description: product id of the respective product
    get:
      summary: Get one product by product id
      description: Get the details of a product
      operationId: get-one-product
      tags:
        - Product
      responses:
        '200':
          description: Product fetching is succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  message:
                    type: string
                  product:
                    $ref: '#/components/schemas/product'
                required:
                  - ok
                  - message
                  - product
    patch:
      summary: Update info of a product
      operationId: patch-product
      description: ''
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                price:
                  type: number
                description:
                  type: string
                stock:
                  type: number
              required:
                - price
                - description
                - stock
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  message:
                    type: string
                required:
                  - ok
                  - message
    delete:
      summary: Delete one product by product id
      description: Delete the product
      operationId: delete-one-product
      tags:
        - Product
      responses:
        '200':
          description: Product deletion is succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  message:
                    type: string
                required:
                  - ok
                  - message
  '/orders/{userID}':
    parameters:
      - name: userID
        in: path
        required: true
        schema:
          type: string
        description: user id of the respective user
    get:
      summary: Get orders by userID.
      description: Get the details of the orders of a user.
      operationId: get-orders-list-by-userid
      tags:
        - Orders
      responses:
        '200':
          description: Orders fetching is succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  message:
                    type: string
                  orders:
                    $ref: '#/components/schemas/order'
                required:
                  - ok
                  - message
                  - orders
  /orders:
    post:
      summary: Create a order
      description: To create/add a new order
      operationId: create-one-order
      tags:
        - Create Order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productID:
                  type: string
                userID:
                  type: string
                addressID:
                  type: string
                quantity:
                  type: number
              required:
                - productID
                - userID
                - addressID
                - quantity
      responses:
        '200':
          description: Order creation is succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  message:
                    type: string
                  orderID:
                    type: string
                required:
                  - ok
                  - message
                  - orderID
  '/orders/{orderID}':
    parameters:
      - name: orderID
        in: path
        required: true
        schema:
          type: string
        description: order id of the respective order
    get:
      summary: Get one order by order id
      description: Get the details of a order
      operationId: get-one-order
      tags:
        - Order
      responses:
        '200':
          description: Order fetching is succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  message:
                    type: string
                  order:
                    $ref: '#/components/schemas/order'
                required:
                  - ok
                  - message
                  - order
    patch:
      summary: Update info of a order
      operationId: patch-order
      description: ''
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: number
              required:
                - quantity
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  message:
                    type: string
                required:
                  - ok
                  - message
    delete:
      summary: Delete one order by order id
      description: Delete the order
      operationId: delete-one-order
      tags:
        - Order
      responses:
        '200':
          description: Order deletion is succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  message:
                    type: string
                required:
                  - ok
                  - message
  '/address/{userID}':
    parameters:
      - name: userID
        in: path
        required: true
        schema:
          type: string
        description: user id of the respective user
    get:
      summary: Get addresses by userID.
      description: Get the details of the addresses of a user.
      operationId: get-address-list-by-userid
      tags:
        - Addresses
      responses:
        '200':
          description: Addresses fetching is succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  message:
                    type: string
                  addresses:
                    $ref: '#/components/schemas/address'
                required:
                  - ok
                  - message
                  - addresses
  /addresses:
    post:
      summary: Create an address
      description: To create/add a new address
      operationId: create-one-address
      tags:
        - Create Address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userID:
                  type: string
                country:
                  type: string
                city:
                  type: string
                streetAddress:
                  type: string
              required:
                - userID
                - country
                - city
                - streetAddress
      responses:
        '200':
          description: Address creation is succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  message:
                    type: string
                  addressID:
                    type: string
                required:
                  - ok
                  - message
                  - addressID
  '/addresses/{addressID}':
    parameters:
      - name: addressID
        in: path
        required: true
        schema:
          type: string
        description: address id of the respective address
    get:
      summary: Get one address by address id
      description: Get the details of a address
      operationId: get-one-address
      tags:
        - Address
      responses:
        '200':
          description: Address fetching is succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  message:
                    type: string
                  address:
                    $ref: '#/components/schemas/address'
                required:
                  - ok
                  - message
                  - address
    patch:
      summary: Update info of a address
      operationId: patch-address
      description: ''
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                country:
                  type: string
                city:
                  type: string
                streetAddress:
                  type: string
              required:
                - country
                - city
                - streetAddress
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  message:
                    type: string
                required:
                  - ok
                  - message
components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: string
          example: 7713b34a-27dc-5347-9fa8-12720f0dddcf
        name:
          type: string
          example: Sample User Name
        email:
          type: string
          example: demo@example.com
        password:
          type: string
          example: sample hashed password
        isAdmin:
          type: boolean
          example: false
        createdAt:
          type: number
        updatedAt:
          type: number
      required:
        - id
        - name
        - email
        - password
        - isAdmin
        - createdAt
        - updatedAt
    product:
      type: object
      properties:
        id:
          type: string
          example: 7713b34a-27dc-5347-9fa8-12720f0dddcf
        name:
          type: string
          example: Sample Product Name
        price:
          type: number
          example: 100
        description:
          type: string
          example: sample product
        stock:
          type: number
          example: 1
        createdAt:
          type: number
        updatedAt:
          type: number
      required:
        - id
        - name
        - price
        - description
        - stock
        - createdAt
        - updatedAt
    order:
      type: object
      properties:
        id:
          type: string
        productID:
          type: string
        userID:
          type: string
        addressID:
          type: string
        quantity:
          type: number
        createdAt:
          type: number
        updatedAt:
          type: number
      required:
        - id
        - productID
        - userID
        - addressID
        - quantity
        - createdAt
        - updatedAt
    address:
      type: object
      properties:
        id:
          type: string
        userID:
          type: string
        country:
          type: string
        city:
          type: string
        streetAddress:
          type: string
        createdAt:
          type: number
        updatedAt:
          type: number
      required:
        - id
        - userID
        - country
        - city
        - streetAddress
        - createdAt
        - updatedAt
